### ISSUE TITLE
NoSuchMethodError after upgrade of kotest to 5.4.0

### ISSUE THREAD

**Issue by otbe** [kotest/kotest-extensions-spring#52]
Hi,

we get the following exception in our tests after upgrade to kotest 5.4.0

```
io.kotest.core.descriptors.TestPath io.kotest.core.descriptors.Descriptor$TestDescriptor.path(boolean)'
java.lang.NoSuchMethodError: 'io.kotest.core.descriptors.TestPath io.kotest.core.descriptors.Descriptor$TestDescriptor.path(boolean)'
	at io.kotest.extensions.spring.SpringTestExtension.methodName$kotest_extensions_spring(SpringTestExtension.kt:126)
	at io.kotest.extensions.spring.SpringTestExtension.method(SpringTestExtension.kt:100)
	at io.kotest.extensions.spring.SpringTestExtension.intercept(SpringTestExtension.kt:68)
	at io.kotest.engine.test.TestExtensions$intercept$execute$1$1.invokeSuspend(TestExtensions.kt:146)
	at io.kotest.engine.test.TestExtensions$intercept$execute$1$1.invoke(TestExtensions.kt)
	at io.kotest.engine.test.TestExtensions$intercept$execute$1$1.invoke(TestExtensions.kt)
	at io.kotest.engine.test.TestExtensions.intercept(TestExtensions.kt:154)
	at io.kotest.engine.test.interceptors.TestCaseExtensionInterceptor.intercept(TestCaseExtensionInterceptor.kt:24)
	at io.kotest.engine.test.TestCaseExecutor$execute$2$1.invokeSuspend(TestCaseExecutor.kt:90)
```

**Comment by Kantis** [comment]
See https://github.com/kotest/kotest/issues/3122

**Comment by sksamuel** [comment]
5.4.1 is released now with fix.
