### ISSUE TITLE
kotest-extensions-spring:1.1.1 doesn't work with kotest 5.4.0

### ISSUE THREAD

**Issue by kochetkov-ma** [kotest/kotest-extensions-spring#53]
build.gradle:
```    
    testImplementation 'io.kotest:kotest-runner-junit5:5.4.0'
    testImplementation ('io.kotest.extensions:kotest-extensions-spring:1.1.1') {
        exclude group: 'io.kotest'
    }
```
kotlin `1.7.10`

Trying to use Constructor Injection > have error

```
Caused by: java.lang.NoSuchMethodError: 'io.kotest.core.descriptors.TestPath io.kotest.core.descriptors.Descriptor$TestDescriptor.path(boolean)'
	at io.kotest.extensions.spring.SpringTestExtension.methodName$kotest_extensions_spring(SpringTestExtension.kt:126)
	at io.kotest.extensions.spring.SpringTestExtension.method(SpringTestExtension.kt:100)
	at io.kotest.extensions.spring.SpringTestExtension.intercept(SpringTestExtension.kt:68)
	at io.kotest.engine.test.TestExtensions$intercept$execute$1$1.invokeSuspend(TestExtensions.kt:146)
```

So you try support deprecated package name via `typealias` - `typealias TestPath = io.kotest.common.TestPath` located `/io/kotest/core/descriptors/descriptor.kt:9`

But, it dosn't work =( 

Apparently kotlin ignores typealias in the type returned in the method and you need to duplicate the method for backward compatibility and make a new version of Kotest or update Kotest in the Spring extension.

**Comment by Kantis** [comment]
See https://github.com/kotest/kotest/issues/3122

**Comment by kochetkov-ma** [comment]
The same issue! Should close as duplicated?

**Comment by sksamuel** [comment]
Fixed in 5.4.1
